//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OHC
{
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET.Business.LINQProvider;
    using System;
    using System.Linq;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Network section BS.
    /// </summary>
    // *** Start programmer edit section *** (networkSectionBS CustomAttributes)

    // *** End programmer edit section *** (networkSectionBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class networkSectionBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (networkSectionBS CustomMembers)

        // *** End programmer edit section *** (networkSectionBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateNetworkSection CustomAttributes)

        // *** End programmer edit section *** (OnUpdateNetworkSection CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateNetworkSection(IIS.OHC.NetworkSection UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateNetworkSection)
            if (UpdatedObject.GetStatus() != ObjectStatus.Deleted)
            {
                var ds = (SQLDataService)DataService;
                var networkareas = ds
                    .Query<NetworkSection>(NetworkSection.Views.NetworkSectionE)
                    .Count(k => k.HeatConsumptionObject.__PrimaryKey == UpdatedObject.HeatConsumptionObject.__PrimaryKey &&
                    k.SectionNumber == UpdatedObject.SectionNumber && k.SectionType == UpdatedObject.SectionType && 
                    k.__PrimaryKey != UpdatedObject.__PrimaryKey);

                if (networkareas > 0)
                    throw new Exception(" Участок сети с таким именем и типом сети уже есть");
            }

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateNetworkSection)
        }
    }
}
