//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OHC
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Q rand checker.
    /// </summary>
    // *** Start programmer edit section *** (QRandChecker CustomAttributes)

    // *** End programmer edit section *** (QRandChecker CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class QRandChecker : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (QRandChecker CustomMembers)

        // *** End programmer edit section *** (QRandChecker CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateHeatConsumptionObject CustomAttributes)

        // *** End programmer edit section *** (OnUpdateHeatConsumptionObject CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateHeatConsumptionObject(IIS.OHC.HeatConsumptionObject UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateHeatConsumptionObject)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateHeatConsumptionObject)
        }
    }
}
