//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OHC
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сетевой район.
    /// </summary>
    // *** Start programmer edit section *** (NetworkArea CustomAttributes)

    // *** End programmer edit section *** (NetworkArea CustomAttributes)
    [AutoAltered()]
    [Caption("Сетевой район")]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "AreaName as \'Area name\'"})]
    [View("NetworkAreaE", new string[] {
            "AreaName as \'Наименование района\'"})]
    [View("NetworkAreaL", new string[] {
            "AreaName as \'Наименование района\'"})]
    public class NetworkArea : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private string fAreaName;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        // *** Start programmer edit section *** (NetworkArea CustomMembers)

        // *** End programmer edit section *** (NetworkArea CustomMembers)

        
        /// <summary>
        /// Название района.
        /// </summary>
        // *** Start programmer edit section *** (NetworkArea.AreaName CustomAttributes)

        // *** End programmer edit section *** (NetworkArea.AreaName CustomAttributes)
        [StrLen(255)]
        public virtual string AreaName
        {
            get
            {
                // *** Start programmer edit section *** (NetworkArea.AreaName Get start)

                // *** End programmer edit section *** (NetworkArea.AreaName Get start)
                string result = this.fAreaName;
                // *** Start programmer edit section *** (NetworkArea.AreaName Get end)

                // *** End programmer edit section *** (NetworkArea.AreaName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NetworkArea.AreaName Set start)

                // *** End programmer edit section *** (NetworkArea.AreaName Set start)
                this.fAreaName = value;
                // *** Start programmer edit section *** (NetworkArea.AreaName Set end)

                // *** End programmer edit section *** (NetworkArea.AreaName Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (NetworkArea.CreateTime CustomAttributes)

        // *** End programmer edit section *** (NetworkArea.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (NetworkArea.CreateTime Get start)

                // *** End programmer edit section *** (NetworkArea.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (NetworkArea.CreateTime Get end)

                // *** End programmer edit section *** (NetworkArea.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NetworkArea.CreateTime Set start)

                // *** End programmer edit section *** (NetworkArea.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (NetworkArea.CreateTime Set end)

                // *** End programmer edit section *** (NetworkArea.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (NetworkArea.Creator CustomAttributes)

        // *** End programmer edit section *** (NetworkArea.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (NetworkArea.Creator Get start)

                // *** End programmer edit section *** (NetworkArea.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (NetworkArea.Creator Get end)

                // *** End programmer edit section *** (NetworkArea.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NetworkArea.Creator Set start)

                // *** End programmer edit section *** (NetworkArea.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (NetworkArea.Creator Set end)

                // *** End programmer edit section *** (NetworkArea.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (NetworkArea.EditTime CustomAttributes)

        // *** End programmer edit section *** (NetworkArea.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (NetworkArea.EditTime Get start)

                // *** End programmer edit section *** (NetworkArea.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (NetworkArea.EditTime Get end)

                // *** End programmer edit section *** (NetworkArea.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NetworkArea.EditTime Set start)

                // *** End programmer edit section *** (NetworkArea.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (NetworkArea.EditTime Set end)

                // *** End programmer edit section *** (NetworkArea.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (NetworkArea.Editor CustomAttributes)

        // *** End programmer edit section *** (NetworkArea.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (NetworkArea.Editor Get start)

                // *** End programmer edit section *** (NetworkArea.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (NetworkArea.Editor Get end)

                // *** End programmer edit section *** (NetworkArea.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NetworkArea.Editor Set start)

                // *** End programmer edit section *** (NetworkArea.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (NetworkArea.Editor Set end)

                // *** End programmer edit section *** (NetworkArea.Editor Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(IIS.OHC.NetworkArea));
                }
            }
            
            /// <summary>
            /// "NetworkAreaE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NetworkAreaE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NetworkAreaE", typeof(IIS.OHC.NetworkArea));
                }
            }
            
            /// <summary>
            /// "NetworkAreaL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NetworkAreaL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NetworkAreaL", typeof(IIS.OHC.NetworkArea));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
