//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OHC
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Участок сети.
    /// </summary>
    // *** Start programmer edit section *** (NetworkSection CustomAttributes)

    // *** End programmer edit section *** (NetworkSection CustomAttributes)
    [BusinessServer("IIS.OHC.networkSectionBS, OHC.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [Caption("Участок сети")]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "SectionNumber as \'Section number\'",
            "SectionType as \'Section type\'",
            "InsulationType as \'Insulation type\'",
            "YearOfInstallation as \'Year of installation\'",
            "InstallationType as \'Installation type\'",
            "Descr_string as \'Descr_string\'"})]
    [View("NetworkSectionE", new string[] {
            "SectionNumber as \'Номер участка\'",
            "SectionType as \'Тип участка\'",
            "InsulationType as \'Тип изоляции\'",
            "YearOfInstallation as \'Год прокладки\'",
            "InstallationType as \'Тип прокладки\'",
            "Descr_string as \'Строка описания\'",
            "HeatConsumptionObject"}, Hidden=new string[] {
            "HeatConsumptionObject"})]
    public class NetworkSection : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private int fSectionNumber;
        
        private IIS.OHC.TSectionType fSectionType;
        
        private int fInsulationType;
        
        private int fYearOfInstallation;
        
        private IIS.OHC.TInstallationType fInstallationType;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private IIS.OHC.HeatConsumptionObject fHeatConsumptionObject;
        
        // *** Start programmer edit section *** (NetworkSection CustomMembers)

        // *** End programmer edit section *** (NetworkSection CustomMembers)

        
        /// <summary>
        /// Номер участка.
        /// </summary>
        // *** Start programmer edit section *** (NetworkSection.SectionNumber CustomAttributes)

        // *** End programmer edit section *** (NetworkSection.SectionNumber CustomAttributes)
        public virtual int SectionNumber
        {
            get
            {
                // *** Start programmer edit section *** (NetworkSection.SectionNumber Get start)

                // *** End programmer edit section *** (NetworkSection.SectionNumber Get start)
                int result = this.fSectionNumber;
                // *** Start programmer edit section *** (NetworkSection.SectionNumber Get end)

                // *** End programmer edit section *** (NetworkSection.SectionNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NetworkSection.SectionNumber Set start)

                // *** End programmer edit section *** (NetworkSection.SectionNumber Set start)
                this.fSectionNumber = value;
                // *** Start programmer edit section *** (NetworkSection.SectionNumber Set end)

                // *** End programmer edit section *** (NetworkSection.SectionNumber Set end)
            }
        }
        
        /// <summary>
        /// Тип участка.
        /// </summary>
        // *** Start programmer edit section *** (NetworkSection.SectionType CustomAttributes)

        // *** End programmer edit section *** (NetworkSection.SectionType CustomAttributes)
        public virtual IIS.OHC.TSectionType SectionType
        {
            get
            {
                // *** Start programmer edit section *** (NetworkSection.SectionType Get start)

                // *** End programmer edit section *** (NetworkSection.SectionType Get start)
                IIS.OHC.TSectionType result = this.fSectionType;
                // *** Start programmer edit section *** (NetworkSection.SectionType Get end)

                // *** End programmer edit section *** (NetworkSection.SectionType Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NetworkSection.SectionType Set start)

                // *** End programmer edit section *** (NetworkSection.SectionType Set start)
                this.fSectionType = value;
                // *** Start programmer edit section *** (NetworkSection.SectionType Set end)

                // *** End programmer edit section *** (NetworkSection.SectionType Set end)
            }
        }
        
        /// <summary>
        /// Тип изоляции.
        /// </summary>
        // *** Start programmer edit section *** (NetworkSection.InsulationType CustomAttributes)

        // *** End programmer edit section *** (NetworkSection.InsulationType CustomAttributes)
        public virtual int InsulationType
        {
            get
            {
                // *** Start programmer edit section *** (NetworkSection.InsulationType Get start)

                // *** End programmer edit section *** (NetworkSection.InsulationType Get start)
                int result = this.fInsulationType;
                // *** Start programmer edit section *** (NetworkSection.InsulationType Get end)

                // *** End programmer edit section *** (NetworkSection.InsulationType Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NetworkSection.InsulationType Set start)

                // *** End programmer edit section *** (NetworkSection.InsulationType Set start)
                this.fInsulationType = value;
                // *** Start programmer edit section *** (NetworkSection.InsulationType Set end)

                // *** End programmer edit section *** (NetworkSection.InsulationType Set end)
            }
        }
        
        /// <summary>
        /// Год прокладки.
        /// </summary>
        // *** Start programmer edit section *** (NetworkSection.YearOfInstallation CustomAttributes)

        // *** End programmer edit section *** (NetworkSection.YearOfInstallation CustomAttributes)
        public virtual int YearOfInstallation
        {
            get
            {
                // *** Start programmer edit section *** (NetworkSection.YearOfInstallation Get start)

                // *** End programmer edit section *** (NetworkSection.YearOfInstallation Get start)
                int result = this.fYearOfInstallation;
                // *** Start programmer edit section *** (NetworkSection.YearOfInstallation Get end)

                // *** End programmer edit section *** (NetworkSection.YearOfInstallation Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NetworkSection.YearOfInstallation Set start)

                // *** End programmer edit section *** (NetworkSection.YearOfInstallation Set start)
                this.fYearOfInstallation = value;
                // *** Start programmer edit section *** (NetworkSection.YearOfInstallation Set end)

                // *** End programmer edit section *** (NetworkSection.YearOfInstallation Set end)
            }
        }
        
        /// <summary>
        /// Тип прокладки.
        /// </summary>
        // *** Start programmer edit section *** (NetworkSection.InstallationType CustomAttributes)

        // *** End programmer edit section *** (NetworkSection.InstallationType CustomAttributes)
        public virtual IIS.OHC.TInstallationType InstallationType
        {
            get
            {
                // *** Start programmer edit section *** (NetworkSection.InstallationType Get start)

                // *** End programmer edit section *** (NetworkSection.InstallationType Get start)
                IIS.OHC.TInstallationType result = this.fInstallationType;
                // *** Start programmer edit section *** (NetworkSection.InstallationType Get end)

                // *** End programmer edit section *** (NetworkSection.InstallationType Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NetworkSection.InstallationType Set start)

                // *** End programmer edit section *** (NetworkSection.InstallationType Set start)
                this.fInstallationType = value;
                // *** Start programmer edit section *** (NetworkSection.InstallationType Set end)

                // *** End programmer edit section *** (NetworkSection.InstallationType Set end)
            }
        }
        
        /// <summary>
        /// Полное описание участка сети.
        /// </summary>
        // *** Start programmer edit section *** (NetworkSection.Descr_string CustomAttributes)

        // *** End programmer edit section *** (NetworkSection.Descr_string CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        [StrLen(255)]
        public virtual string Descr_string
        {
            get
            {
                // *** Start programmer edit section *** (NetworkSection.Descr_string Get)

                return null;
                // *** End programmer edit section *** (NetworkSection.Descr_string Get)
            }
            set
            {
                // *** Start programmer edit section *** (NetworkSection.Descr_string Set)

                // *** End programmer edit section *** (NetworkSection.Descr_string Set)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (NetworkSection.CreateTime CustomAttributes)

        // *** End programmer edit section *** (NetworkSection.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (NetworkSection.CreateTime Get start)

                // *** End programmer edit section *** (NetworkSection.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (NetworkSection.CreateTime Get end)

                // *** End programmer edit section *** (NetworkSection.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NetworkSection.CreateTime Set start)

                // *** End programmer edit section *** (NetworkSection.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (NetworkSection.CreateTime Set end)

                // *** End programmer edit section *** (NetworkSection.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (NetworkSection.Creator CustomAttributes)

        // *** End programmer edit section *** (NetworkSection.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (NetworkSection.Creator Get start)

                // *** End programmer edit section *** (NetworkSection.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (NetworkSection.Creator Get end)

                // *** End programmer edit section *** (NetworkSection.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NetworkSection.Creator Set start)

                // *** End programmer edit section *** (NetworkSection.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (NetworkSection.Creator Set end)

                // *** End programmer edit section *** (NetworkSection.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (NetworkSection.EditTime CustomAttributes)

        // *** End programmer edit section *** (NetworkSection.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (NetworkSection.EditTime Get start)

                // *** End programmer edit section *** (NetworkSection.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (NetworkSection.EditTime Get end)

                // *** End programmer edit section *** (NetworkSection.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NetworkSection.EditTime Set start)

                // *** End programmer edit section *** (NetworkSection.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (NetworkSection.EditTime Set end)

                // *** End programmer edit section *** (NetworkSection.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (NetworkSection.Editor CustomAttributes)

        // *** End programmer edit section *** (NetworkSection.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (NetworkSection.Editor Get start)

                // *** End programmer edit section *** (NetworkSection.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (NetworkSection.Editor Get end)

                // *** End programmer edit section *** (NetworkSection.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NetworkSection.Editor Set start)

                // *** End programmer edit section *** (NetworkSection.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (NetworkSection.Editor Set end)

                // *** End programmer edit section *** (NetworkSection.Editor Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.OHC.HeatConsumptionObject.
        /// </summary>
        // *** Start programmer edit section *** (NetworkSection.HeatConsumptionObject CustomAttributes)

        // *** End programmer edit section *** (NetworkSection.HeatConsumptionObject CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "HeatConsumtionObject"})]
        public virtual IIS.OHC.HeatConsumptionObject HeatConsumptionObject
        {
            get
            {
                // *** Start programmer edit section *** (NetworkSection.HeatConsumptionObject Get start)

                // *** End programmer edit section *** (NetworkSection.HeatConsumptionObject Get start)
                IIS.OHC.HeatConsumptionObject result = this.fHeatConsumptionObject;
                // *** Start programmer edit section *** (NetworkSection.HeatConsumptionObject Get end)

                // *** End programmer edit section *** (NetworkSection.HeatConsumptionObject Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NetworkSection.HeatConsumptionObject Set start)

                // *** End programmer edit section *** (NetworkSection.HeatConsumptionObject Set start)
                this.fHeatConsumptionObject = value;
                // *** Start programmer edit section *** (NetworkSection.HeatConsumptionObject Set end)

                // *** End programmer edit section *** (NetworkSection.HeatConsumptionObject Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(IIS.OHC.NetworkSection));
                }
            }
            
            /// <summary>
            /// "NetworkSectionE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NetworkSectionE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NetworkSectionE", typeof(IIS.OHC.NetworkSection));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
    
    /// <summary>
    /// Detail array of NetworkSection.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfNetworkSection CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfNetworkSection CustomAttributes)
    public class DetailArrayOfNetworkSection : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.OHC.DetailArrayOfNetworkSection members)

        // *** End programmer edit section *** (IIS.OHC.DetailArrayOfNetworkSection members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type NetworkSection by index.
        /// </summary>
        /// <summary>
        /// Adds object with type NetworkSection.
        /// </summary>
        public DetailArrayOfNetworkSection(IIS.OHC.HeatConsumptionObject fHeatConsumptionObject) : 
                base(typeof(NetworkSection), ((ICSSoft.STORMNET.DataObject)(fHeatConsumptionObject)))
        {
        }
        
        public IIS.OHC.NetworkSection this[int index]
        {
            get
            {
                return ((IIS.OHC.NetworkSection)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.OHC.NetworkSection dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
