//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OHC
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип прокладки трубопровода.
    /// </summary>
    // *** Start programmer edit section *** (TInstallationType CustomAttributes)

    // *** End programmer edit section *** (TInstallationType CustomAttributes)
    public enum TInstallationType
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TInstallationType.наземный CustomAttributes)

        // *** End programmer edit section *** (TInstallationType.наземный CustomAttributes)
        наземный,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TInstallationType.подземный CustomAttributes)

        // *** End programmer edit section *** (TInstallationType.подземный CustomAttributes)
        подземный,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TInstallationType.по__подвалу CustomAttributes)

        // *** End programmer edit section *** (TInstallationType.по__подвалу CustomAttributes)
        по__подвалу,
    }
}
