//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OHC
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип участка.
    /// </summary>
    // *** Start programmer edit section *** (TSectionType CustomAttributes)

    // *** End programmer edit section *** (TSectionType CustomAttributes)
    public enum TSectionType
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TSectionType.внутренний CustomAttributes)

        // *** End programmer edit section *** (TSectionType.внутренний CustomAttributes)
        внутренний,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TSectionType.наружный CustomAttributes)

        // *** End programmer edit section *** (TSectionType.наружный CustomAttributes)
        наружный,
    }
}
